services:
  backend_model:
    image: nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    expose:
      - "8100"
    ports:
      - "5439:8100"
    volumes:
      - ../../models_backend:/home/models_backend
      - ../../hotdog:/home/hotdog
    working_dir: /home/models_backend
    command: >
      bash -c "apt-get update -y
      && apt-get upgrade -y
      && apt-get install -y build-essential
      && apt-get install -y python3-pip python3-dev python-is-python3
      && apt-get install -y libssl-dev libffi-dev libncurses5-dev zlib1g zlib1g-dev libreadline-dev libbz2-dev libsqlite3-dev liblzma-dev make gcc libgl1 libglib2.0-0
      && apt-get install -y libpython3-dev libpq-dev python3-psycopg2 python3-venv
      && rm -rf /var/lib/apt/lists/*
      && python3 -m venv .venv
      && source .venv/bin/activate
      && yes|pip install .
      && nvidia-smi
      && tail -f /dev/null"
    networks:
      deep_learning_backend_subnet:
        ipv4_address: ${BACKEND_IP}

networks:
  deep_learning_backend_subnet:
    external: true
